on:
  issue_comment:
    types: [created, edited]

jobs:
  first:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - run: echo '${{ github.event.comment.body }}'
